version: '3.8'
services:
  postgresql:
    container_name: my_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "1234"

  bot:
    build: 
      context: bot/
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: "1234"
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/
    depends_on:
      - mongo

  api:
    build: 
      context: api/
    ports:
      - "4000:4000"
    environment:
      DB_NAME: 'postgres'
      DB_HOST: 'my_postgres'  
      DB_PORT: 5432  
      DB_USER: 'postgres'
      DB_PASS: '1234'
      CLIENT_ID: CLIENT_ID
      CLIENT_SECRET: SECRET
      REDIRECT_URI: http://localhost:4000/api/auth/discord/callback
      SECRET_KEY_JWT: SECRET
    depends_on:
      - postgresql

  client:
    build: 
      client/
    ports:
      - "8080:8080"
volumes:
  postgres_data: